<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="default.aspx.cs" Inherits="MyTest._default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        name: <asp:TextBox ID="txtName" runat="server" /><br />
        Message:<asp:TextBox ID="txtMsg" runat="server" /><br />
        <asp:Button ID="btnSend" runat="server" Text="Send" />
        <div id="container" >

        </div>

            <!--Script references. -->
        <!--Reference the jQuery library. -->
        <script src="Scripts/jquery-1.6.4.min.js"></script>
        <!--Reference the SignalR library. -->
        <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>
        <!--Reference the autogenerated SignalR hub script. -->
        <script src="signalr/hubs"></script>

        <script type="text/javascript">
            $(function () {
                var chat = $.connection.hub;
                chat.client.broadcast = function (name, message) {
                    var n 
                }
            })
        </script>
    </div>
    </form>
</body>
</html>
